export type Product = {
  id: string;
  slug: string;
  name: string;
  category: 'bedding' | 'bathrobes' | 'toiletries' | 'candles' | 'minibar' | 'pillows';
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  stock: number;
  badge?: 'Bestseller' | 'New' | 'Sale' | 'Limited';
  description: string;
  images: string[];
  variants: { label: string; options: string[] }[];
  amenities: string[];
  featured: boolean;
  createdAt: string;
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'egyptian-cotton-sheets',
    name: 'Egyptian Cotton Sheet Set',
    category: 'bedding',
    price: 289,
    originalPrice: 349,
    rating: 4.9,
    reviewCount: 234,
    stock: 45,
    badge: 'Bestseller',
    description: 'Luxurious 800-thread-count Egyptian cotton sheets that transform your bedroom into a five-star suite. Silky smooth, breathable, and designed to last.',
    images: [
      'https://picsum.photos/seed/bed1/800/800',
      'https://picsum.photos/seed/bed1a/800/800',
      'https://picsum.photos/seed/bed1b/800/800',
    ],
    variants: [
      { label: 'Size', options: ['Queen', 'King', 'California King'] },
      { label: 'Color', options: ['White', 'Ivory', 'Champagne'] },
    ],
    amenities: ['Premium Cotton', 'Hotel Grade', 'Handcrafted', 'Free Shipping', '30-day Return'],
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    slug: 'silk-duvet-cover',
    name: 'Mulberry Silk Duvet Cover',
    category: 'bedding',
    price: 425,
    rating: 4.8,
    reviewCount: 156,
    stock: 28,
    badge: 'New',
    description: 'Pure mulberry silk duvet cover with a 22-momme weight. Temperature regulating and hypoallergenic for the ultimate sleep experience.',
    images: [
      'https://picsum.photos/seed/bed2/800/800',
      'https://picsum.photos/seed/bed2a/800/800',
    ],
    variants: [
      { label: 'Size', options: ['Queen', 'King'] },
      { label: 'Color', options: ['Pearl', 'Champagne', 'Charcoal'] },
    ],
    amenities: ['Pure Silk', 'Hypoallergenic', 'Temperature Regulating', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-01',
  },
  {
    id: '3',
    slug: 'linen-bedding-set',
    name: 'French Linen Bedding Set',
    category: 'bedding',
    price: 345,
    rating: 4.7,
    reviewCount: 189,
    stock: 52,
    description: 'Stone-washed French linen that gets softer with every wash. Breathable, elegant, and effortlessly luxurious.',
    images: [
      'https://picsum.photos/seed/bed3/800/800',
      'https://picsum.photos/seed/bed3a/800/800',
    ],
    variants: [
      { label: 'Size', options: ['Queen', 'King'] },
      { label: 'Color', options: ['Natural', 'Sage', 'Terracotta'] },
    ],
    amenities: ['French Linen', 'Stone Washed', 'Breathable', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-10',
  },
  {
    id: '4',
    slug: 'velvet-throw-blanket',
    name: 'Velvet Throw Blanket',
    category: 'bedding',
    price: 165,
    rating: 4.6,
    reviewCount: 98,
    stock: 67,
    badge: 'Bestseller',
    description: 'Plush velvet throw with a subtle sheen. Perfect for draping over your bed or sofa for instant elegance.',
    images: ['https://picsum.photos/seed/bed4/800/800'],
    variants: [
      { label: 'Color', options: ['Burgundy', 'Navy', 'Emerald', 'Blush'] },
    ],
    amenities: ['Plush Velvet', 'Machine Washable', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    slug: 'turkish-cotton-robe',
    name: 'Turkish Cotton Bathrobe',
    category: 'bathrobes',
    price: 195,
    rating: 4.9,
    reviewCount: 312,
    stock: 89,
    badge: 'Bestseller',
    description: 'Ultra-absorbent Turkish cotton robe with a shawl collar. The same robe you find in luxury spas worldwide.',
    images: [
      'https://picsum.photos/seed/robe1/800/800',
      'https://picsum.photos/seed/robe1a/800/800',
    ],
    variants: [
      { label: 'Size', options: ['S/M', 'L/XL'] },
      { label: 'Color', options: ['White', 'Charcoal', 'Navy'] },
    ],
    amenities: ['Turkish Cotton', 'Spa Grade', 'Ultra Absorbent', 'Free Shipping'],
    featured: true,
    createdAt: '2024-01-05',
  },
  {
    id: '6',
    slug: 'waffle-robe',
    name: 'Waffle Weave Robe',
    category: 'bathrobes',
    price: 145,
    rating: 4.7,
    reviewCount: 203,
    stock: 74,
    description: 'Lightweight waffle weave robe that is quick-drying and breathable. Perfect for warmer climates.',
    images: ['https://picsum.photos/seed/robe2/800/800'],
    variants: [
      { label: 'Size', options: ['S/M', 'L/XL'] },
      { label: 'Color', options: ['White', 'Sand', 'Slate'] },
    ],
    amenities: ['Waffle Weave', 'Quick Dry', 'Lightweight', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-14',
  },
  {
    id: '7',
    slug: 'silk-robe',
    name: 'Pure Silk Kimono Robe',
    category: 'bathrobes',
    price: 285,
    rating: 4.8,
    reviewCount: 127,
    stock: 34,
    badge: 'Limited',
    description: 'Hand-finished silk kimono robe with delicate embroidery. A statement piece for your morning ritual.',
    images: [
      'https://picsum.photos/seed/robe3/800/800',
      'https://picsum.photos/seed/robe3a/800/800',
    ],
    variants: [
      { label: 'Size', options: ['One Size'] },
      { label: 'Color', options: ['Ivory', 'Blush', 'Midnight'] },
    ],
    amenities: ['Pure Silk', 'Hand Embroidered', 'Limited Edition', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-05',
  },
  {
    id: '8',
    slug: 'luxury-soap-set',
    name: 'Artisan Soap Collection',
    category: 'toiletries',
    price: 68,
    rating: 4.6,
    reviewCount: 445,
    stock: 156,
    badge: 'Bestseller',
    description: 'Set of four handcrafted soaps infused with essential oils. Bergamot, lavender, eucalyptus, and rose.',
    images: ['https://picsum.photos/seed/soap1/800/800'],
    variants: [
      { label: 'Scent Set', options: ['Classic', 'Citrus', 'Floral'] },
    ],
    amenities: ['Handcrafted', 'Natural Ingredients', 'Cruelty Free', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-10',
  },
  {
    id: '9',
    slug: 'body-lotion',
    name: 'Nourishing Body Lotion',
    category: 'toiletries',
    price: 52,
    rating: 4.7,
    reviewCount: 289,
    stock: 203,
    description: 'Rich, fast-absorbing body lotion with shea butter and vitamin E. Leaves skin silky and hydrated.',
    images: ['https://picsum.photos/seed/lotion1/800/800'],
    variants: [
      { label: 'Scent', options: ['Unscented', 'Vanilla', 'Coconut'] },
    ],
    amenities: ['Shea Butter', 'Vitamin E', 'Paraben Free', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-01',
  },
  {
    id: '10',
    slug: 'bath-salts',
    name: 'Dead Sea Bath Salts',
    category: 'toiletries',
    price: 45,
    rating: 4.8,
    reviewCount: 178,
    stock: 112,
    badge: 'New',
    description: 'Mineral-rich bath salts from the Dead Sea. Soak away stress and rejuvenate tired muscles.',
    images: ['https://picsum.photos/seed/salt1/800/800'],
    variants: [
      { label: 'Scent', options: ['Lavender', 'Eucalyptus', 'Rose'] },
    ],
    amenities: ['Dead Sea Minerals', 'Therapeutic', 'Natural', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-10',
  },
  {
    id: '11',
    slug: 'shampoo-conditioner-set',
    name: 'Luxury Hair Care Duo',
    category: 'toiletries',
    price: 78,
    rating: 4.5,
    reviewCount: 156,
    stock: 89,
    description: 'Sulfate-free shampoo and conditioner enriched with argan oil. For all hair types.',
    images: ['https://picsum.photos/seed/hair1/800/800'],
    variants: [],
    amenities: ['Sulfate Free', 'Argan Oil', 'All Hair Types', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-25',
  },
  {
    id: '12',
    slug: 'amber-candle',
    name: 'Amber & Oud Candle',
    category: 'candles',
    price: 85,
    rating: 4.9,
    reviewCount: 567,
    stock: 145,
    badge: 'Bestseller',
    description: 'Hand-poured soy candle with notes of amber, oud, and sandalwood. 60-hour burn time.',
    images: [
      'https://picsum.photos/seed/candle1/800/800',
      'https://picsum.photos/seed/candle1a/800/800',
    ],
    variants: [
      { label: 'Size', options: ['Small (8oz)', 'Large (16oz)'] },
    ],
    amenities: ['Hand Poured', 'Soy Wax', '60hr Burn', 'Free Shipping'],
    featured: true,
    createdAt: '2024-01-08',
  },
  {
    id: '13',
    slug: 'fig-candle',
    name: 'Mediterranean Fig Candle',
    category: 'candles',
    price: 85,
    rating: 4.8,
    reviewCount: 423,
    stock: 132,
    description: 'Fresh fig with hints of bergamot and cedarwood. Evokes a sun-drenched Mediterranean garden.',
    images: ['https://picsum.photos/seed/candle2/800/800'],
    variants: [
      { label: 'Size', options: ['Small (8oz)', 'Large (16oz)'] },
    ],
    amenities: ['Hand Poured', 'Soy Wax', '60hr Burn', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-05',
  },
  {
    id: '14',
    slug: 'jasmine-candle',
    name: 'Night Jasmine Candle',
    category: 'candles',
    price: 85,
    rating: 4.7,
    reviewCount: 298,
    stock: 98,
    badge: 'New',
    description: 'Intoxicating jasmine blended with white musk and vanilla. A romantic evening scent.',
    images: ['https://picsum.photos/seed/candle3/800/800'],
    variants: [
      { label: 'Size', options: ['Small (8oz)', 'Large (16oz)'] },
    ],
    amenities: ['Hand Poured', 'Soy Wax', '60hr Burn', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-12',
  },
  {
    id: '15',
    slug: 'candle-trio',
    name: 'Signature Candle Trio',
    category: 'candles',
    price: 215,
    originalPrice: 255,
    rating: 4.9,
    reviewCount: 189,
    stock: 67,
    badge: 'Sale',
    description: 'Our three bestselling candles in travel sizes. Perfect for gifting or sampling.',
    images: ['https://picsum.photos/seed/candle4/800/800'],
    variants: [],
    amenities: ['Hand Poured', 'Soy Wax', 'Gift Ready', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-30',
  },
  {
    id: '16',
    slug: 'chocolate-truffles',
    name: 'Belgian Chocolate Truffles',
    category: 'minibar',
    price: 38,
    rating: 4.8,
    reviewCount: 512,
    stock: 234,
    badge: 'Bestseller',
    description: 'Assorted Belgian chocolate truffles in a luxury gift box. 12 pieces.',
    images: ['https://picsum.photos/seed/choc1/800/800'],
    variants: [
      { label: 'Assortment', options: ['Classic', 'Dark', 'Mixed'] },
    ],
    amenities: ['Belgian Chocolate', 'Gift Box', 'Handmade', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-12',
  },
  {
    id: '17',
    slug: 'gourmet-nuts',
    name: 'Roasted Nut Collection',
    category: 'minibar',
    price: 28,
    rating: 4.6,
    reviewCount: 234,
    stock: 178,
    description: 'Premium roasted almonds, cashews, and pistachios with sea salt and rosemary.',
    images: ['https://picsum.photos/seed/nuts1/800/800'],
    variants: [],
    amenities: ['Gourmet', 'Small Batch', 'Resealable', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-08',
  },
  {
    id: '18',
    slug: 'tea-collection',
    name: 'Artisan Tea Collection',
    category: 'minibar',
    price: 45,
    rating: 4.7,
    reviewCount: 345,
    stock: 156,
    description: 'Curated selection of 12 premium loose-leaf teas from around the world.',
    images: ['https://picsum.photos/seed/tea1/800/800'],
    variants: [],
    amenities: ['Loose Leaf', 'Organic', 'Gift Box', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-18',
  },
  {
    id: '19',
    slug: 'champagne-truffles',
    name: 'Champagne Truffles',
    category: 'minibar',
    price: 42,
    rating: 4.9,
    reviewCount: 267,
    stock: 89,
    badge: 'Limited',
    description: 'White chocolate truffles infused with real champagne. Elegant and indulgent.',
    images: ['https://picsum.photos/seed/champ1/800/800'],
    variants: [],
    amenities: ['Champagne Infused', 'Limited Edition', 'Gift Box', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-01',
  },
  {
    id: '20',
    slug: 'down-pillow',
    name: 'European Down Pillow',
    category: 'pillows',
    price: 165,
    rating: 4.8,
    reviewCount: 423,
    stock: 112,
    badge: 'Bestseller',
    description: 'Premium European white down pillow with 700 fill power. Cloud-like comfort.',
    images: ['https://picsum.photos/seed/pillow1/800/800'],
    variants: [
      { label: 'Firmness', options: ['Soft', 'Medium', 'Firm'] },
      { label: 'Size', options: ['Standard', 'King'] },
    ],
    amenities: ['European Down', '700 Fill', 'Hotel Grade', 'Free Shipping'],
    featured: false,
    createdAt: '2024-01-22',
  },
  {
    id: '21',
    slug: 'memory-foam-pillow',
    name: 'Contour Memory Foam Pillow',
    category: 'pillows',
    price: 125,
    rating: 4.7,
    reviewCount: 567,
    stock: 145,
    description: 'Ergonomic memory foam pillow with cooling gel layer. Perfect for side and back sleepers.',
    images: ['https://picsum.photos/seed/pillow2/800/800'],
    variants: [
      { label: 'Height', options: ['Low', 'Medium', 'High'] },
    ],
    amenities: ['Memory Foam', 'Cooling Gel', 'Ergonomic', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-12',
  },
  {
    id: '22',
    slug: 'silk-pillowcase',
    name: 'Mulberry Silk Pillowcase',
    category: 'pillows',
    price: 89,
    rating: 4.9,
    reviewCount: 789,
    stock: 234,
    badge: 'Bestseller',
    description: '22-momme mulberry silk pillowcase. Reduces hair frizz and prevents sleep creases.',
    images: ['https://picsum.photos/seed/pillow3/800/800'],
    variants: [
      { label: 'Size', options: ['Standard', 'King'] },
      { label: 'Color', options: ['White', 'Champagne', 'Charcoal'] },
    ],
    amenities: ['Pure Silk', 'Anti-Aging', 'Hair Care', 'Free Shipping'],
    featured: true,
    createdAt: '2024-01-28',
  },
  {
    id: '23',
    slug: 'buckwheat-pillow',
    name: 'Organic Buckwheat Pillow',
    category: 'pillows',
    price: 95,
    rating: 4.5,
    reviewCount: 178,
    stock: 67,
    badge: 'New',
    description: 'Adjustable buckwheat hull pillow that molds to your head and neck. Naturally cooling.',
    images: ['https://picsum.photos/seed/pillow4/800/800'],
    variants: [
      { label: 'Size', options: ['Standard', 'King'] },
    ],
    amenities: ['Organic', 'Adjustable', 'Cooling', 'Free Shipping'],
    featured: false,
    createdAt: '2024-03-08',
  },
  {
    id: '24',
    slug: 'reed-diffuser',
    name: 'Luxury Reed Diffuser',
    category: 'candles',
    price: 72,
    rating: 4.6,
    reviewCount: 234,
    stock: 98,
    description: 'Elegant reed diffuser with amber and sandalwood fragrance. Lasts up to 4 months.',
    images: ['https://picsum.photos/seed/diffuser1/800/800'],
    variants: [
      { label: 'Scent', options: ['Amber & Sandalwood', 'White Tea', 'Bergamot'] },
    ],
    amenities: ['Long Lasting', 'Elegant Design', 'Refillable', 'Free Shipping'],
    featured: false,
    createdAt: '2024-02-20',
  },
];
